spring:
  profiles:
    active:
    - dev
---
spring:
  profies: dev
  application:
    name: microservicecloud-config-nanhua-dev 
---
spring:
  profies: test
  application:
    name: microservicecloud-config-nanhua-test
# 请保存为utf-8格式